### PR TITLE
blake256 dependency fix

### PR DESCRIPTION
**Pull request by peterzen**
Fixed decred/blake256 dependency reference to point to dchest/blake256

### CODE REVIEW

**Comment by dajohi** [comment]
a bunch moved.

dcrutil went to dcrd/dcrutil
dcrrpcclient went to dcrd/rpcclient

**Comment by peterzen** [comment]
I gave it a go to fix those links as well but noticed other issues as well with the recent repo reorgs and I don't have the time ATM to properly test the changes.  The PR works as a hotfix for the immediate compilation problem.

**Comment by chappjc** [comment]
Thanks @peterzen .  I'll have a look at this today.

**Comment by chappjc** [comment]
Please see https://github.com/chappjc/dcrspy/pull/4

**Pull request closed without merging**
